DROP USER group5GC CASCADE;
DROP USER testUser1;
DROP ROLE applicationAdmin2;
DROP ROLE applicationUser2;
DROP TABLESPACE GUITAR_COLLECTION INCLUDING CONTENTS AND DATAFILES;


ALTER USER group5GC
  IDENTIFIED BY group5password
  ACCOUNT UNLOCK
  DEFAULT TABLESPACE GUITAR_COLLECTION
  QUOTA 20M ON GUITAR_COLLECTION;

-- Modify the attributes for testUser1
ALTER USER testUser1
  IDENTIFIED BY test1Password
  ACCOUNT UNLOCK
  DEFAULT TABLESPACE GUITAR_COLLECTION
  QUOTA 10M ON GUITAR_COLLECTION; 